export const APP_INFO_NAMESPACE = 'APP_INFO_NAMESPACE' + '.';
export const INIT_FLAG = APP_INFO_NAMESPACE + 'INIT_FLAG';
export const START_USING_DATE = APP_INFO_NAMESPACE + 'START_USING_DATE';

export const USER_INFO_NAMESPACE = 'USER_INFO_NAMESPACE' + '.';
export const USERNAME = USER_INFO_NAMESPACE + 'user';
export const AVATAR_CODE = USER_INFO_NAMESPACE + 'AVATAR_CODE';
